spring:
  config:
    import:
      - "optional:classpath:bot.yaml"
      - "optional:classpath:attribute.yaml"

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
    redis-channel:
      new-registration: create-registration
      confirmed: confirmed
      cancel: cancel


logging:
  level:
    org.springframework: INFO
    ru.pereguzochka.telegram_bot: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"

bot-backend:
  host: http://192.168.31.103
  port: 8081
