spring:
  config:
    import:
      - "optional:classpath:bot.yaml"
      - "optional:classpath:attribute.yaml"

  data:
    redis-channel:
      new-registration: create-registration
      confirmed: confirmed
      cancel: cancel


logging:
  level:
    org.springframework: INFO
    ru.pereguzochka.telegram_bot: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"

bot-backend:
  host: http://localhost
  port: 8081
