server:
  port: 8072

spring:
  config:
    import:
      - "optional:classpath:bot-dev.yaml"
      - "optional:classpath:attribute.yaml"

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6377}
    redis-channel:
      new-registration: create-registration
      confirmed: confirmed
      cancel: cancel


logging:
  level:
    org.springframework: INFO
    ru.pereguzochka.telegram_bot: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"

bot-backend:
  host: localhost
  port: 8071