server:
  port: 8082

spring:
  config:
    import:
      - "optional:classpath:bot-prod.yaml"
      - "optional:classpath:attribute.yaml"

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
    redis-channel:
      new-registration: create-registration
      new-group-registration: create-group-registration
      confirmed: confirmed
      group-confirmed: group-confirmed
      cancel: cancel
      group-cancel: group-cancel

logging:
  level:
    org.springframework: INFO
    ru.pereguzochka.telegram_bot: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"

bot-backend:
  host: http://192.168.31.103
  port: 8081


# для тестового коммита